[platformio]
default_envs = uno

[env:uno]
platform = atmelavr@5.1.0
board = uno
framework = arduino
monitor_speed = 9600
build_flags = -DLED_PIN=13

[env:esp32dev]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
monitor_speed = 9600
build_flags = -DLED_PIN=2
